//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.TaskScheduler.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedulerJob
    {
        public TaskSchedulerJob()
        {
            this.EmailContents = new HashSet<EmailContent>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ExecutionIntervalSeconds { get; set; }
        public Nullable<System.DateTime> LastExecution { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RowCreatedTimeStamp { get; set; }
    
        public virtual ICollection<EmailContent> EmailContents { get; set; }
    }
}
