//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentUserMap
    {
        public int Id { get; set; }
        public int AssignmentId { get; set; }
        public int TraineeId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
