//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentSubtopicContentMap
    {
        public int Id { get; set; }
        public int AssignmentId { get; set; }
        public int SubtopicContentId { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual SubtopicContent SubtopicContent { get; set; }
    }
}
