//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeReviewMetaData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeReviewMetaData()
        {
            this.CodeReviewTags = new HashSet<CodeReviewTag>();
        }
    
        public int CodeReviewMetaDataId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public int AddedBy { get; set; }
        public int AddedFor { get; set; }
        public Nullable<bool> IsDiscarded { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> SystemRating { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Feedback Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeReviewTag> CodeReviewTags { get; set; }
    }
}
