//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeReviewTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeReviewTag()
        {
            this.CodeReviewPoints = new HashSet<CodeReviewPoint>();
        }
    
        public int CodeReviewTagId { get; set; }
        public int CodeReviewMetaDataId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CodeReviewMetaData CodeReviewMetaData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeReviewPoint> CodeReviewPoints { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
