//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubtopicDiscussion
    {
        public int Id { get; set; }
        public int CourseSubtopicId { get; set; }
        public string Text { get; set; }
        public bool IsHidden { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CourseSubtopic CourseSubtopic { get; set; }
        public virtual User User { get; set; }
    }
}
