//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrRatingCalcWeightConfig
    {
        public int Id { get; set; }
        public int ReviewPointTypeId { get; set; }
        public float Weight { get; set; }
        public int CrRatingCalcConfigId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual CodeReviewPointType CodeReviewPointType { get; set; }
        public virtual CrRatingCalcConfig CrRatingCalcConfig { get; set; }
        public virtual User LastModifiedBy { get; set; }
    }
}
