//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrRatingCalcConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrRatingCalcConfig()
        {
            this.CrRatingCalcRangeConfigs = new HashSet<CrRatingCalcRangeConfig>();
            this.CrRatingCalcWeightConfigs = new HashSet<CrRatingCalcWeightConfig>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User LastModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrRatingCalcRangeConfig> CrRatingCalcRangeConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrRatingCalcWeightConfig> CrRatingCalcWeightConfigs { get; set; }
    }
}
