//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumUserHelpPost
    {
        public ForumUserHelpPost()
        {
            this.ForumUserHelpThreads = new HashSet<ForumUserHelpThread>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int AddedBy { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ForumUserHelpCategory ForumUserHelpCategory { get; set; }
        public virtual ForumUserHelpStatu ForumUserHelpStatu { get; set; }
        public virtual ICollection<ForumUserHelpThread> ForumUserHelpThreads { get; set; }
    }
}
