//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningMap
    {
        public LearningMap()
        {
            this.LearningMapCourseMappings = new HashSet<LearningMapCourseMapping>();
            this.LearningMapUserMappings = new HashSet<LearningMapUserMapping>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public int Duration { get; set; }
        public bool IsCourseRestricted { get; set; }
        public int TeamId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LearningMapCourseMapping> LearningMapCourseMappings { get; set; }
        public virtual ICollection<LearningMapUserMapping> LearningMapUserMappings { get; set; }
    }
}
