//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedulerJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskSchedulerJob()
        {
            this.EmailContents = new HashSet<EmailContent>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ExecutionIntervalSeconds { get; set; }
        public Nullable<System.DateTime> LastExecution { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RowCreatedTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailContent> EmailContents { get; set; }
    }
}
